[metadata]
  name = "find-provs"
  author = "adin"

[global]
  plan = "dht"
  case = "find-providers"
  total_instances = 1000
  builder = "docker:go"
  runner = "cluster:k8s"
  [global.build_config]
    push_registry = true
    registry_type = "aws"

[[groups]]
  id = "balsam-undialable-provider-small"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:f9925d8ca293"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "4"
      record_count = "1"
      timeout_secs = "600"
      undialable = "true"

[[groups]]
  id = "balsam-undialable-provider-medium"
  [groups.instances]
    count = 15
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:d50b49c3a283"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "4"
      record_count = "1"
      timeout_secs = "600"
      undialable = "true"

[[groups]]
  id = "balsam-undialable-provider-large"
  [groups.instances]
    count = 100
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:31b4ce6ac9fd"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "4"
      record_count = "1"
      timeout_secs = "600"
      undialable = "true"

[[groups]]
  id = "balsam-dialable-provider-small"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:3bfe28dbd9fe"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "4"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "balsam-dialable-provider-medium"
  [groups.instances]
    count = 15
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:810aaf639a7c"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "4"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "balsam-dialable-provider-large"
  [groups.instances]
    count = 100
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:757b85988ae1"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "4"
      record_count = "1"
      timeout_secs = "600"

[[groups]]
  id = "balsam-undialable-searcher"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:ce32b3feb9b7"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "4"
      search_records = "true"
      timeout_secs = "600"
      undialable = "true"

[[groups]]
  id = "balsam-dialable-searcher"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:66d9edad497e"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "4"
      search_records = "true"
      timeout_secs = "600"

[[groups]]
  id = "balsam-undialable-passive"
  [groups.instances]
    count = 495
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:c35f6c98d34b"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "4"
      timeout_secs = "600"
      undialable = "true"

[[groups]]
  id = "balsam-dialable-passive"
  [groups.instances]
    count = 250
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:24b2649a5c42"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "4"
      timeout_secs = "600"

[[groups]]
  id = "balsam-bs"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:daf5dcfc7683"
    [groups.run.test_params]
      bootstrapper = "true"
      bs_strategy = "1"
      bucket_size = "4"
      timeout_secs = "600"


